### PR TITLE
Update to Lutris 0.5.2

### PR DESCRIPTION
**Pull request by RobLoach**
[Lutris 0.5.2](https://github.com/lutris/lutris/releases/tag/v0.5.2) is out. This allows removal of one of the manually maintained patches:
https://github.com/lutris/lutris/pull/1977

### CODE REVIEW

**Review by RobLoach — COMMENTED** [review]
Need to update the other patch.

**Review by gasinvein — APPROVED** [review]
LGTM

**Review by LeandroStanger — APPROVED** [review]

**Comment by RobLoach** [comment]
The other patch will need to be updated before we merge this one.

**Comment by RobLoach** [comment]
Mind testing this?

**Comment by gasinvein** [comment]
@RobLoach Updated in what way? It applies just fine, Lutris is able to launch Steam games.

**Comment by RobLoach** [comment]
The patch wasn't applying against 0.5.2, so I updated the diff....

```
➜  lutris git:(master) git checkout v0.5.2
➜  lutris git:(8bacffa) wget https://raw.githubusercontent.com/RobLoach/net.lutris.Lutris/net.lutris.Lutris/patches/0002-Use-xdg-open-to-run-Steam-games-if-running-in-flatpa.patch
➜  lutris git:(8bacffa) ✗ git apply 0002-Use-xdg-open-to-run-Steam-games-if-running-in-flatpa.patch
error: patch failed: lutris/util/linux.py:104
error: lutris/util/linux.py: patch does not apply
```

With the updated diff, it applies cleanly now.

**Comment by gasinvein** [comment]
Strange, it did work for me in flatpak-builder, just with some fuzz:
```
Applying patch 0001-Use-xdg-open-to-run-Steam-games-if-running-in-flatpa.patch
patching file lutris/runners/steam.py
Hunk #1 succeeded at 189 (offset 1 line).
Hunk #2 succeeded at 212 (offset 1 line).
Hunk #3 succeeded at 329 (offset 6 lines).
patching file lutris/util/linux.py
Hunk #1 succeeded at 108 with fuzz 2 (offset 4 lines).
Hunk #2 succeeded at 206 with fuzz 1 (offset 4 lines).
```

**Review by gasinvein — APPROVED** [review]
Anyway, it seems to work.

**Comment by RobLoach** [comment]
Thanks for trying a build! :+1:

**Pull request merged**
