### PR TITLE
Update some modules to newest versions

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Review by gasinvein — CHANGES_REQUESTED** [review]
Usbutils newer than 070 requires udev newer than 175, which is part of systemd and not available standalone.

**Comment by gasinvein** [comment]
@LeandroStanger did you test it local build?

**Comment by LeandroStanger** [comment]
@gasinvein No

**Review by gasinvein — COMMENTED** [review]
@LeandroStanger did you test local build of this branch? If not, please do.

**Review by gasinvein — APPROVED** [review]

**Comment by gasinvein** [comment]
We need to make sure it won't break anything. Especially I suspect Pillow to break something, version 6.0.0 didn't land yet even in Arch Linux.

**Comment by LeandroStanger** [comment]
```
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[1246/2814] Building CXX object Source...sources/UnifiedSource-23a5fd0e-3.cpp.o
ninja: build stopped: subcommand failed.
Error: module webkitgtk: Processo filho concluiu com código 1
```

**Pull request merged**
