### PR TITLE
Add extension point for runners

### PR DESCRIPTION
**Pull request by gasinvein**
With this we can build external programs (i.e. Lutris runners) as flatpak extensions.
Discovered problems:
- [ ] Different runners use different libs, all of them are added to ld path. This may break something.
- [ ] Lutris seems unable to detect installed runner, even when it's in PATH. Manually setting path to runner binary works.

### CODE REVIEW

**Comment by gasinvein** [comment]
Existing flatpak apps may be reused with minimal changes, see gasinvein/org.libretro.RetroArch@61496a071a926486eb9e2a5ba9b9cc8a26215c8f for example.

**Comment by RobLoach** [comment]
Regarding [gasinvein:lutris-runner](https://github.com/flathub/org.libretro.RetroArch/compare/master...gasinvein:lutris-runner/master), it seems like a lot of work to expose the runner. Is there no way to have a Flatpak execute another Flatpak executable?

**Comment by gasinvein** [comment]
>it seems like a lot of work to expose the runner

Almost all of the changes are related to changing install prefix. Amount of changed lines could be reduced if paths aren't hardcoded and repeated, e.g. if we put them in some variable of something like this.

>Is there no way to have a Flatpak execute another Flatpak executable?

AFAIK no, not without involving host commands. flatpak/flatpak#2436 and flatpak/flatpak#2846 seems related.

**Comment by gasinvein** [comment]
Now [the changes](/flathub/org.libretro.RetroArch/compare/master...gasinvein:lutris-runner/master) to RetroArch manifest are small and simple enough, I think.

**Review by LeandroStanger — APPROVED** [review]

**Pull request merged**
