### PR TITLE
Add prebuild retroarch dependencies

### LINKED ISSUE #34: Add Libudev.so.1 In Order for Libretro Cores To Work
Libretro cores require libudev.so.1. Apparently, this is not part of the Lutris runtime and it needs to be added to the flatpak bundle.

### PR DESCRIPTION
**Pull request by gasinvein**
Fixes #34

### CODE REVIEW

**Comment by gasinvein** [comment]
Once flathub/shared-modules#57 is merged, it can be used instead of eudev. Yet neither udev implementation would really work inside the sandbox.

**Comment by valentindavid** [comment]
@gasinvein is `libudev.so.0` not needed? I think steam runtime for example needs it. So maybe we should have both versions.

**Comment by valentindavid** [comment]
Nevermind, the steam runtime provides it. So if a game uses it, it will be OK.

**Comment by gasinvein** [comment]
Modern distros don't provide `libudev.so.0` at all and yet Steam works. Anyway, we plan to use the already-flatpak'ed Steam to run Steam games.
Arch provides [libudev0-shim](https://github.com/archlinux/libudev0-shim) compatibility library. Maybe we could borrow it?

**Pull request merged**
