### PR TITLE
Bundle wine

### PR DESCRIPTION
**Pull request by gasinvein**
This is an example of how we can bundle wine. Making it an extension gives some advantages. Specifically it can be updated separately from Lutris and makes multiarch builds slightly easier.

### CODE REVIEW

**Comment by lionirdeadman** [comment]
It might be worthwhile to make the extension generic so other applications can depend on it.

**Comment by gasinvein** [comment]
@lionirdeadman AFAIK it's impossible to plug an extension of one app to another. Yet the manifest for building the extension can be reused with minimum changes.

**Comment by LeandroStanger** [comment]
**Add**
- [ ] [Wine-gecko](https://dl.winehq.org/wine/wine-gecko)
- [ ] [Wine-mono](https://dl.winehq.org/wine/wine-mono)

**Comment by gasinvein** [comment]
Since #37 we can build Wine as a generic extension. This PR is not needed anymore.

**Pull request closed without merging**
