### PR TITLE
Explicitly add ld path for .Compat.i386 extension

### PR DESCRIPTION
**Pull request by gasinvein**
See https://github.com/flathub/flathub/pull/926#issuecomment-489156990

### CODE REVIEW

**Comment by gasinvein** [comment]
@valentindavid is this ok?

**Comment by valentindavid** [comment]
This seems fine. In Steam there was also first line:
```
include /run/flatpak/ld.so.conf.d/app-*-org.freedesktop.Platform.GL32.*.conf
```

I do not remember exactly what case it was for, but I think this is important when using GL extensions, like mesa-git, or some provided by the operating system. I do not think nvidia needs that. We can try without it. And if there is some issue we can put it as well later.

**Comment by gasinvein** [comment]
Maybe adding `add-ld-path: .` to the extension definition (instead of `ld.so.conf` file) would be better?

**Comment by valentindavid** [comment]
There was issue with priority. So we had to make the app add it manually. Unfortunately. Supporting i386 was a bit special,  so we decided against making the logic behind extensions in flatpak more complicated.

**Pull request merged**
